models:

  - name: dim_geo
    config:
      contract:
        enforced: true
    columns:
      - name: pk
        data_type: integer
        tests:
          - unique
          - not_null
      - name: country_code
        data_type: string
      - name: country
        data_type: string

  - name: fact_government_balance
    config:
      contract:
        enforced: true
    columns:
      - name: pk
        data_type: bigint
        tests:
          - unique
          - not_null
      - name: document_date
        data_type: integer
      - name: current_value
        data_type: bigint
        # FKs
      - name: fk_unit
        data_type: integer
        tests:
          - relationships:
              to: ref('dim_unit')
              field: pk
      - name: fk_sector
        data_type: integer
        tests:
          - relationships:
              to: ref('dim_sector')
              field: pk
      - name: fk_national_accounts
        data_type: integer
        tests:
          - relationships:
              to: ref('dim_national_accounts')
              field: pk
      - name: fk_geo
        data_type: integer
        tests:
          - relationships:
              to: ref('dim_geo')
              field: pk

  - name: dim_sector
    config:
      contract:
        enforced: true
    columns:
      - name: pk
        data_type: integer
        tests:
          - unique
          - not_null
      - name: sector_code
        data_type: string
      - name: sector_label
        data_type: string

  - name: dim_unit
    config:
      contract:
        enforced: true
    columns:
      - name: pk
        data_type: integer
        tests:
          - unique
          - not_null
      - name: unit_code
        data_type: string
      - name: unit_label
        data_type: string

  - name: dim_national_accounts
    config:
      contract:
        enforced: true
    columns:
      - name: pk
        data_type: integer
        tests:
          - unique
          - not_null
      - name: LEVEL_1_DESCRIPTION
        data_type: string
      - name: LEVEL_2_DESCRIPTION
        data_type: string
      - name: LEVEL_3_DESCRIPTION
        data_type: string
